services:
  postgres:
    image: postgres:16-alpine
    container_name: votacao-postgres
    environment:
      POSTGRES_DB: votacao
      POSTGRES_USER: votacao
      POSTGRES_PASSWORD: votacao
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
